# Generated by Django 3.2.12 on 2022-02-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentBooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('appointment_time', models.DateTimeField()),
                ('appointment_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RenameField(
            model_name='beautician',
            old_name='student',
            new_name='customer',
        ),
    ]
