# Generated by Django 3.2.12 on 2022-02-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentBooking', '0002_auto_20220228_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='appointment_date',
        ),
    ]
